ALTER TABLE public.upgrade DROP CONSTRAINT upgrade_request_id_fk;
ALTER TABLE public.upgrade DROP CONSTRAINT upgrade_non_admin_username_fk;
ALTER TABLE public.start_course DROP CONSTRAINT start_course_request_id_fk;
ALTER TABLE public.start_course DROP CONSTRAINT start_course_non_admin_username_fk;
ALTER TABLE public.start_course DROP CONSTRAINT start_course_lesson_id_fk;
ALTER TABLE public.reference DROP CONSTRAINT reference_content_id_fk;
ALTER TABLE public.reference DROP CONSTRAINT reference_course_id_fk;
ALTER TABLE public."like" DROP CONSTRAINT like_user_username_fk;
ALTER TABLE public."like" DROP CONSTRAINT like_post_id_fk;
ALTER TABLE public.handout DROP CONSTRAINT handout_content_id_fk;
ALTER TABLE public.handout DROP CONSTRAINT handout_user_username_fk;
ALTER TABLE public.enroll DROP CONSTRAINT enroll_course_id_fk;
ALTER TABLE public.enroll DROP CONSTRAINT enroll_non_admin_username_fk;
ALTER TABLE public."check" DROP CONSTRAINT check_admin_username_fk;
ALTER TABLE public."check" DROP CONSTRAINT check_request_id_fk;
ALTER TABLE public.bookmark DROP CONSTRAINT bookmark_user_username_fk;
ALTER TABLE public.bookmark DROP CONSTRAINT bookmark_post_id_fk;
ALTER TABLE public.book DROP CONSTRAINT book_content_id_fk;
ALTER TABLE public.book DROP CONSTRAINT book_user_username_fk;
ALTER TABLE public.answer DROP CONSTRAINT answer_user_username_fk;
ALTER TABLE public.answer DROP CONSTRAINT answer_topic_lesson_fk;
ALTER TABLE public.answer DROP CONSTRAINT answer_question_post_id_fk;
ALTER TABLE public.question DROP CONSTRAINT question_user_username_fk;
ALTER TABLE public.question DROP CONSTRAINT question_topic_lesson_fk;
ALTER TABLE public.question DROP CONSTRAINT question_sample_test_id_fk;
ALTER TABLE public.post DROP CONSTRAINT post_user_username_fk;
ALTER TABLE public.post DROP CONSTRAINT post_topic_lesson_fk;
ALTER TABLE public.course DROP CONSTRAINT course_lesson_id_fk;
ALTER TABLE public.course DROP CONSTRAINT course_user_username_fk;
ALTER TABLE public.topic DROP CONSTRAINT topic_lesson_id_fk;
ALTER TABLE public.sample_test DROP CONSTRAINT sample_test_lesson_lesson_id_fk;
ALTER TABLE public.non_admin DROP CONSTRAINT non_admin_user_username_fk;
ALTER TABLE public.content DROP CONSTRAINT content_user_username_fk;
ALTER TABLE public.admin DROP CONSTRAINT admin_username_fkey;
DROP TABLE public.upgrade;
DROP TABLE public.start_course;
DROP TABLE public.reference;
DROP TABLE public."like";
DROP TABLE public.handout;
DROP TABLE public.enroll;
DROP TABLE public."check";
DROP TABLE public.bookmark;
DROP TABLE public.book;
DROP TABLE public.answer;
DROP TABLE public.question;
DROP TABLE public.post;
DROP TABLE public.course;
DROP TABLE public.topic;
DROP TABLE public.sample_test;
DROP TABLE public.non_admin;
DROP TABLE public.content;
DROP TABLE public.admin;
DROP TABLE public."user";
DROP TABLE public.request;
DROP TABLE public.lesson;


DROP FUNCTION public.add_attendee();
DROP FUNCTION public.add_content();
DROP FUNCTION public.add_post();
DROP FUNCTION public.add_published_posts();
DROP FUNCTION public.add_request();
DROP FUNCTION public.add_user();
DROP FUNCTION public.attend_failure();
DROP FUNCTION public.can_not_change_content();
DROP FUNCTION public.can_not_change_post();
DROP FUNCTION public.can_not_change_request();
DROP FUNCTION public.can_not_change_user();
DROP FUNCTION public.change_post_edit_time();
DROP FUNCTION public.check_capacity();
DROP FUNCTION public.check_holder_of_course();

DROP TYPE public.age;
DROP TYPE public.date;
DROP TYPE public."e-mail";
DROP TYPE public.id_number;
DROP TYPE public.time;
DROP TYPE public.url;
DROP TYPE public.user_type;

DROP SEQUENCE public.random_int_seq RESTRICT;

DROP FUNCTION public.make_random_id();
DROP FUNCTION public.process_request();
DROP FUNCTION public.pseudo_encrypt(INTEGER);
DROP FUNCTION public.upgrade_to_instructor();